server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    # 支持通过服务发现来定位host name
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      # zipkin  抽样比例(取值0~1之间) 在默认情况下，该值为0.1
      probability: 1.0

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.25.210:3306/db2021?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yang
    password: ASdf!@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunday.entities
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    register-with-eureka: true #是否注册到eureka，当前server不注册
    fetch-registry: true #表示不需要检索服务
    service-url:
#      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  # 与eureka交互的地址查询服务和注册服务的地址
      defaultZone: http://eureka7001.com:7001/eureka/  # 与eureka交互的地址查询服务和注册服务的地址
  instance:
    instance-id: order80

