server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/illeagalName/springconfig.git
          search-paths: /**
          username:
          password:
      label: master
  rabbitmq:
    host: 123.56.25.210
    port: 5672
    username: yang
    password:

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh' # busrefresh 也行，但是curl -X POST 'http://localhost:3344/actuator/busrefresh/cloud-config-client:3355'  这里面必须是busrefresh
  endpoint:
    health:
      show-details: always
