server:
  port: 8006
spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: 123.56.25.210
      port: 8500
      discovery:
        service-name: ${spring.application.name} #对外暴露的服务名
        heartbeat:
          enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.25.210:3306/db2021?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yang
    password: ASdf!@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunday.entities
  configuration:
    map-underscore-to-camel-case: true
