server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: 123.56.25.210   #rabbitmq 服务器的地址
    port: 5672           #rabbitmq 服务器端口
    username: yang       #rabbitmq 用户名
    password:            #rabbitmq 密码
    virtual-host: /       #虚拟路径
  cloud:
    stream:
      bindings: #服务的整合处理
        sendMsg-out-0: #这个是消息通道的名称 --->输出通道
          destination: studyExchange    #exchange名称,交换模式默认是topic;把SpringCloud stream的消息输出通道绑定到RabbitMQ的studyExchange交换器。
        send2Msg-out-0: #这个是消息通道的名称 --->输出通道
          destination: study2Exchange    #exchange名称,交换模式默认是topic;把SpringCloud stream的消息输出通道绑定到RabbitMQ的studyExchange交换器。
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5 #超过了5秒的间隔
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    instance-id: send-8801.com
    prefer-ip-address: true #访问的路径变为IP地址


