server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #是否注册到eureka，当前server不注册
    fetch-registry: false #表示不需要检索服务
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  # 与eureka交互的地址查询服务和注册服务的地址
      defaultZone: http://eureka7001.com:7001/eureka/  # 与eureka交互的地址查询服务和注册服务的地址
#  server:
#    enable-self-preservation: true #自我保护
#    eviction-interval-timer-in-ms: 300000 #清除无效节点的时间间隔，默认是60000ms(60s)