server:
  port: 80

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.25.210:3306/db2021?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: yang
    password: ASdf!@
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.25.210:8848
        namespace: 0c6bb070-442b-4a5d-902e-161d52f48206

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunday.entities
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

nacos:
  service:
    payment: http://cloud-payment-service